### ISSUE TITLE
v2 Checklist

### ISSUE THREAD

**Issue by englercj** [englercj/resource-loader#72]
- [x] Allow arbitrary query strings for specific resources and all resources (#68)
- [x] Complete the skipped tests
- [x] Write a test to reproduce #66 and fix it
- [x] Implement a Font loader (#5)
